//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWizNW.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationDown")]
        public global::CtrlWiz.NW.UI.Models.Function NV_LTrigger {
            get {
                return ((global::CtrlWiz.NW.UI.Models.Function)(this["NV_LTrigger"]));
            }
            set {
                this["NV_LTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MoveSprint")]
        public global::CtrlWiz.NW.UI.Models.Function NV_LStick {
            get {
                return ((global::CtrlWiz.NW.UI.Models.Function)(this["NV_LStick"]));
            }
            set {
                this["NV_LStick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ElevationUp")]
        public global::CtrlWiz.NW.UI.Models.Function NV_RTrigger {
            get {
                return ((global::CtrlWiz.NW.UI.Models.Function)(this["NV_RTrigger"]));
            }
            set {
                this["NV_RTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ShortestDistance")]
        public global::CtrlWiz.NW.UI.Models.Function NV_RBumber {
            get {
                return ((global::CtrlWiz.NW.UI.Models.Function)(this["NV_RBumber"]));
            }
            set {
                this["NV_RBumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UnhideAll")]
        public global::CtrlWiz.NW.UI.Models.Function NV_YButton {
            get {
                return ((global::CtrlWiz.NW.UI.Models.Function)(this["NV_YButton"]));
            }
            set {
                this["NV_YButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeselectAll")]
        public global::CtrlWiz.NW.UI.Models.Function NV_BButton {
            get {
                return ((global::CtrlWiz.NW.UI.Models.Function)(this["NV_BButton"]));
            }
            set {
                this["NV_BButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SelectDeselect")]
        public global::CtrlWiz.NW.UI.Models.Function NV_AButton {
            get {
                return ((global::CtrlWiz.NW.UI.Models.Function)(this["NV_AButton"]));
            }
            set {
                this["NV_AButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HideUnhide")]
        public global::CtrlWiz.NW.UI.Models.Function NV_XButton {
            get {
                return ((global::CtrlWiz.NW.UI.Models.Function)(this["NV_XButton"]));
            }
            set {
                this["NV_XButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Look")]
        public global::CtrlWiz.NW.UI.Models.Function NV_RStick {
            get {
                return ((global::CtrlWiz.NW.UI.Models.Function)(this["NV_RStick"]));
            }
            set {
                this["NV_RStick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NextViewpoint")]
        public global::CtrlWiz.NW.UI.Models.Function NV_StartButton {
            get {
                return ((global::CtrlWiz.NW.UI.Models.Function)(this["NV_StartButton"]));
            }
            set {
                this["NV_StartButton"] = value;
            }
        }
    }
}
