//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWiz.RVT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CtrlWiz.RVT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ActivateController {
            get {
                object obj = ResourceManager.GetObject("ActivateController", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivateController.
        /// </summary>
        internal static string ActivateControllerButtonName {
            get {
                return ResourceManager.GetString("ActivateControllerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Controller.
        /// </summary>
        internal static string ActivateControllerButtonText {
            get {
                return ResourceManager.GetString("ActivateControllerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Controller.
        /// </summary>
        internal static string ActivateControllerButtonToolTip {
            get {
                return ResourceManager.GetString("ActivateControllerButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureRequest.
        /// </summary>
        internal static string FeatureRequestButtonName {
            get {
                return ResourceManager.GetString("FeatureRequestButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Request.
        /// </summary>
        internal static string FeatureRequestButtonText {
            get {
                return ResourceManager.GetString("FeatureRequestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Request.
        /// </summary>
        internal static string FeatureRequestButtonToolTip {
            get {
                return ResourceManager.GetString("FeatureRequestButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help28 {
            get {
                object obj = ResourceManager.GetObject("Help28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControllerMap.
        /// </summary>
        internal static string HelpButtonName {
            get {
                return ResourceManager.GetString("HelpButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Map.
        /// </summary>
        internal static string HelpButtonText {
            get {
                return ResourceManager.GetString("HelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Map.
        /// </summary>
        internal static string HelpButtonToolTip {
            get {
                return ResourceManager.GetString("HelpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControllerMap.
        /// </summary>
        internal static string HelpClassName {
            get {
                return ResourceManager.GetString("HelpClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Idea {
            get {
                object obj = ResourceManager.GetObject("Idea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon License {
            get {
                object obj = ResourceManager.GetObject("License", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseButtonName {
            get {
                return ResourceManager.GetString("LicenseButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseButtonText {
            get {
                return ResourceManager.GetString("LicenseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseButtonToolTip {
            get {
                return ResourceManager.GetString("LicenseButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox One Controller.
        /// </summary>
        internal static string RibbonPanelName {
            get {
                return ResourceManager.GetString("RibbonPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpeedSettings.
        /// </summary>
        internal static string SpeedSettingsButtonName {
            get {
                return ResourceManager.GetString("SpeedSettingsButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Settings.
        /// </summary>
        internal static string SpeedSettingsButtonText {
            get {
                return ResourceManager.GetString("SpeedSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Settings.
        /// </summary>
        internal static string SpeedSettingsButtonToolTip {
            get {
                return ResourceManager.GetString("SpeedSettingsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CtrlWiz.
        /// </summary>
        internal static string TabName {
            get {
                return ResourceManager.GetString("TabName", resourceCulture);
            }
        }
    }
}
