//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CtrlWiz.License.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CtrlWiz.License.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32f0fa8cbb119f39b7dc72f5479abc2d.
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 576239.
        /// </summary>
        internal static string ProductIdNW {
            get {
                return ResourceManager.GetString("ProductIdNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 585987.
        /// </summary>
        internal static string ProductIdRVT {
            get {
                return ResourceManager.GetString("ProductIdRVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CtrlWiz - Xbox Controller for Navis.
        /// </summary>
        internal static string ProductNameNW {
            get {
                return ResourceManager.GetString("ProductNameNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CtrlWiz - Xbox Controller for Revit.
        /// </summary>
        internal static string ProductNameRVT {
            get {
                return ResourceManager.GetString("ProductNameRVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6F339D1A-8B8C-4FC0-8587-AA74F99785D7.
        /// </summary>
        internal static string TempNW {
            get {
                return ResourceManager.GetString("TempNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E3AE4B3D-1651-4D12-9C45-B48C4D14C9DA.
        /// </summary>
        internal static string TempRVT {
            get {
                return ResourceManager.GetString("TempRVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104612.
        /// </summary>
        internal static string VendorId {
            get {
                return ResourceManager.GetString("VendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buidfore.
        /// </summary>
        internal static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
    }
}
